lilisblog/blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path(r'', views.blog_list, name='blog_list'),
    path(r'<int:article_id>/', views.blog_detail, name='blog_detail'),
]

lilisblog/lilisblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')), #新增
]

lilisblog/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class BlogArticles (models.Model):
    title = models.CharField(max_length=300)
    #ForeignKey(外键)对应多对一，外键要定义在"多"的一方
    #本例通过author字段规定了文章与用户的关系，多篇文章可以对应一个用户，即文章对用户是"多对一"
    #related_name="blog-posts"的作用是，允许通过类User反向查询到BlogArticles，这个参数我们可以不设置，Django会默认以模型的小写作为反向关联名
    #以后从User对象反向关联到他所写的BlogArticles，就可以使用user.blog_posts了
    author = models.ForeignKey(User, related_name="blog_posts", on_delete=models.CASCADE)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ("-publish",) #publish的倒序排序。此处是元祖，不要忘写后面的逗号

    def __str__(self):
        return self.title #对应后台文章列表中的默认显式字段

lilisblog/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogArticles


def blog_list(request):
    blogs = BlogArticles.objects.all()
    return render(request, "blog/blog_list.html", {"blogs": blogs})


def blog_detail(request, article_id):
    article = get_object_or_404(BlogArticles, id=article_id)
    pub = article.publish
    return render(request, "blog/blog_detail.html", {"article": article, "publish": pub})

# Create your views here.

lilisblog/blog/templates/blog/blog_list.html
{% extends "base.html" %}

{% block title %} blog titles {% endblock %}

{% block content %}
<div class="row text-center vertical-middlw-sm">
    <h1>我的博客</h1>
</div>
<div class="row">
    <div class="col-xs-12 col-md-8">
        <ul>
            {% for blog in blogs %}
            <li><a href="{{blog.id}}">{{blog.title}}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-xs-6 col-md-4">
        <h2>莉莉安</h2>
        <img width="200px" src="https://mmbiz.qpic.cn/mmbiz_jpg/50ZAC2pjue1m3aXiccoFZRU1icIUCROtkRn5X9mpJRZicZr71gEuSdfrKCtlziawJ0icyWNM2YN49QYpJXuEC3ibVNZA/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1">
    </div>
</div>
{% endblock %}

lilisblog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
{% include "header.html" %}
<div class="container">
    {% block content %} {% endblock %}
</div>
{% include "footer.html" %}
{% block javascript %} {% endblock %}
</body>
</html>

lilisblog/templates/blog/blog_detail.html
{% extends "base.html" %}

{% block title %} blog titles {% endblock %}

{% block content %}
<div class="row text-center vertical-middlw-sm">
    <h1>{{article.title}}</h1>
</div>
<div class="row">
    <div class="col-xs-12 col-md-8">
        <p class="text-center">
            <span>{{article.author.username}}</span>
            <span style="margin-left:20px">{{publish}}</span>
        </p>
        <div>
            {{article.body}}
        </div>
    </div>
    <div class="col-xs-6 col-md-4">
        <h2>莉莉安</h2>
        <img width="200px" src="https://upload-images.jianshu.io/upload_images/2739773-dc365a4733b4c677?imageMogr2/auto-orient/strip|imageView2/2/w/900/format/webp">
    </div>
</div>
{% endblock %}

lilisblog/templates/blog/blog_list.html
{% extends "base.html" %}

{% block title %} blog titles {% endblock %}

{% block content %}
<div class="row text-center vertical-middlw-sm">
    <h1>我的博客</h1>
</div>
<div class="row">
    <div class="col-xs-12 col-md-8">
        <ul>
            {% for blog in blogs %}
            <li><a href="{{blog.id}}">{{blog.title}}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-xs-6 col-md-4">
        <h2>莉莉安</h2>
        <img width="200px" src="https://upload-images.jianshu.io/upload_images/2739773-dc365a4733b4c677?imageMogr2/auto-orient/strip|imageView2/2/w/900/format/webp">
    </div>
</div>
{% endblock %}

lilisblog/templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">copy right</p>
</div>

lilisblog/templates/header.html
{% load static %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href=""><img src="{% static '/images/logo.png' %}" width="100px"></a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'blog:blog_list' %}">BLOG</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right:20px">
                <li><a href="#">LOGIN</a></li>
            </ul>
        </div>
    </nav>
</div>